
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Worktrip.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Airport
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Airport()
    {

        this.UserMiscTaxInfoes = new HashSet<UserMiscTaxInfo>();

    }


    public string Code { get; set; }

    public string Name { get; set; }

    public string CityCode { get; set; }

    public string CityName { get; set; }

    public string CountryName { get; set; }

    public string CountryCode { get; set; }

    public string Timezone { get; set; }

    public string Lat { get; set; }

    public string Lon { get; set; }

    public Nullable<int> NumAirports { get; set; }

    public Nullable<bool> City { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserMiscTaxInfo> UserMiscTaxInfoes { get; set; }

}

}
