//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worktrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreparerNote
    {
        public int Id { get; set; }
        public string PreparerId { get; set; }
        public string UserId { get; set; }
        public string Notes { get; set; }
        public System.DateTime Date { get; set; }
        public int TaxYear { get; set; }
        public string NoteCreatorId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
