//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worktrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMiscTaxInfo
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int TaxYear { get; set; }
        public string BaseAirportCode { get; set; }
        public Nullable<int> DaysInTrainingOrAway { get; set; }
        public Nullable<double> DriverLayoverTips { get; set; }
        public Nullable<double> TotalSpentLayoverTransportation { get; set; }
        public Nullable<double> TransactionalFees { get; set; }
        public Nullable<double> ClothingFees { get; set; }
        public Nullable<double> LaundryFees { get; set; }
        public Nullable<double> FlightGearLuggageFees { get; set; }
        public Nullable<double> TechPurchasesFees { get; set; }
        public Nullable<double> CellphoneBill { get; set; }
        public Nullable<double> InternetBill { get; set; }
        public Nullable<double> IdentityFees { get; set; }
        public Nullable<double> UnreimbursedExpenses { get; set; }
        public string Airline { get; set; }
        public string PreparerNotes { get; set; }
        public Nullable<decimal> TaxReturn { get; set; }
        public string TaxReturnDocument { get; set; }
        public Nullable<double> LayoversPerDiem { get; set; }
        public string DLState { get; set; }
        public Nullable<bool> InternationalLayovers { get; set; }
        public Nullable<bool> Married { get; set; }
        public Nullable<bool> Dependent { get; set; }
        public Nullable<bool> StudentLoans { get; set; }
        public Nullable<bool> Stocks { get; set; }
        public Nullable<bool> House { get; set; }
        public Nullable<bool> HSA { get; set; }
        public Nullable<bool> C1098T { get; set; }
        public Nullable<bool> C1099R { get; set; }
        public Nullable<bool> Other { get; set; }
        public Nullable<bool> OwnBusiness { get; set; }
        public Nullable<bool> ScheduleK1 { get; set; }
        public Nullable<bool> C1099G { get; set; }
        public Nullable<bool> C1099INT { get; set; }
        public Nullable<bool> MultipleW2s { get; set; }
        public Nullable<bool> NewHire { get; set; }
        public Nullable<bool> Itemize { get; set; }
        public Nullable<bool> DriveToWork { get; set; }
        public Nullable<bool> FlyReserveDays { get; set; }
        public string Spouse { get; set; }
        public Nullable<double> TrainingExpenses { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual User User { get; set; }
    }
}
