
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Worktrip.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserToPreparer
{

    public int Id { get; set; }

    public string UserId { get; set; }

    public string PreparerId { get; set; }

    public int StatusId { get; set; }

    public int Year { get; set; }

    public Nullable<decimal> Fee { get; set; }

    public Nullable<decimal> PaidAmount { get; set; }

    public string ColorCode { get; set; }

    public Nullable<System.DateTime> FirstModified { get; set; }

    public string PromoCode { get; set; }



    public virtual Status Status { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
