
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Worktrip.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserMiscTaxInfo
{

    public int Id { get; set; }

    public string UserId { get; set; }

    public int TaxYear { get; set; }

    public string BaseAirportCode { get; set; }

    public Nullable<int> DaysInTrainingOrAway { get; set; }

    public Nullable<double> DriverLayoverTips { get; set; }

    public Nullable<double> TotalSpentLayoverTransportation { get; set; }

    public Nullable<double> TransactionalFees { get; set; }

    public Nullable<double> ClothingFees { get; set; }

    public Nullable<double> LaundryFees { get; set; }

    public Nullable<double> FlightGearLuggageFees { get; set; }

    public Nullable<double> TechPurchasesFees { get; set; }

    public Nullable<double> CellphoneBill { get; set; }

    public Nullable<double> InternetBill { get; set; }

    public Nullable<double> IdentityFees { get; set; }

    public Nullable<double> UnreimbursedExpenses { get; set; }

    public string Airline { get; set; }

    public string PreparerNotes { get; set; }

    public Nullable<decimal> TaxReturn { get; set; }

    public string TaxReturnDocument { get; set; }

    public Nullable<double> LayoversPerDiem { get; set; }

    public string DLState { get; set; }



    public virtual Airport Airport { get; set; }

    public virtual User User { get; set; }

}

}
