//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worktrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuestion
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string AskedBy { get; set; }
        public string Answer { get; set; }
        public string AnsweredBy { get; set; }
        public int TaxYear { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
