//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worktrip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorktripEntities : DbContext
    {
        public WorktripEntities()
            : base("name=WorktripEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airline> Airlines { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserPerDiem> UserPerDiems { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<UserMiscDoc> UserMiscDocs { get; set; }
        public virtual DbSet<UserQuestion> UserQuestions { get; set; }
        public virtual DbSet<UserMiscTaxInfo> UserMiscTaxInfoes { get; set; }
        public virtual DbSet<UserToPreparer> UserToPreparers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserActionsLog> UserActionsLogs { get; set; }
        public virtual DbSet<PerDiemRate> PerDiemRates { get; set; }
    }
}
